### ISSUE TITLE
Provide an AppImage file

### ISSUE THREAD

**Issue by pierremtb** [lirios/calculator#11] opened 2017-03-18 20:49 UTC

**Comment by probonopd** [comment] 2017-03-21 22:57
Check out https://github.com/lirios/browser/blob/develop/.travis.yml - you should be able to transfer this over pretty much 1:1. Let me know if you are running into issues.

**Comment by pierremtb** [comment] 2017-03-24 23:09
It works like a charm, thanks @probonopd

**Comment by pierremtb** [comment] 2017-03-24 23:09
https://transfer.sh/SzFLx/Liri_Calculator-git.9c4e973-x86_64.AppImage

**Comment by pierremtb** [comment] 2017-03-25 10:40
Some platform lib is missing in AppImage build. The rest works perfectly, but the FileDialog componennt can't be loaded:
```
ERROR: No native FileDialog implementation available.
Qt Labs Platform requires Qt Widgets on this setup.
Add 'QT += widgets' to .pro and create QApplication in main().
```

Any idea @probonopd ?

**Comment by probonopd** [comment] 2017-03-25 10:42
@pierremtb not really but check out http://doc.qt.io/qt-5/qtwidgets-index.html

**Comment by Aldrog** [comment] 2017-03-25 11:45
I don't think adding dependency on QtWidgets is a good idea (there's actually no reason to do it).
The problem is that it cannot find platform native dialogs.

**Comment by probonopd** [comment] 2017-03-25 11:48
@Aldrog where do "platform native dialogs" live? Is that a qml import?

**Comment by plfiorini** [comment] 2017-03-25 11:56
exactly @Aldrog, Qt uses dialogs implemented with QtWidgets just as a fallback when the platform theme plugin is not found or doesn't provide native dialogs.

**Comment by plfiorini** [comment] 2017-03-25 11:59
@probonopd they live in each Qt `platform theme` plugin or `QPA` plugin that implements a `platform theme`. So if you are running a Qt app on GNOME it's likely the `gtk` platform theme, on KDE it's their platform theme plugin developed under the KDE umbrella. On Liri OS it's our platform theme plugin (yes at some point Liri OS will have full material dialogs).

**Comment by probonopd** [comment] 2017-03-25 12:35
So if you want to use these, you would have to deploy them in the AppImage. Also see https://github.com/probonopd/AppImageKit/issues/125

**Comment by plfiorini** [comment] 2018-04-03 06:15
Almost there, we need to add a package to the container:

```sh
./Liri_Calculator-git-20180402-191749-da2cf37-x86_64.AppImage
QQmlApplicationEngine failed to load component
qrc:/ui/Main.qml:31 module "Qt.labs.settings" is not installed
```

**Comment by probonopd** [comment] 2018-04-03 06:32
There is another issue as well:

`AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'GLIBCXX_3.4.21' not found`. Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6 for the solution.

Reference:
https://github.com/AppImage/appimage.github.io/pull/493

**Comment by plfiorini** [comment] 2018-04-05 07:12
Added missing Qt.labs.settings now I have the following error:

```
file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Error decoding: file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/icons/navigation/expand_less.svg: Unsupported image format
file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Error decoding: file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/icons/action/history.svg: Unsupported image format
file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Error decoding: file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/icons/navigation/close.svg: Unsupported image format
file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Error decoding: file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/icons/action/list.svg: Unsupported image format
file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Error decoding: file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/icons/content/save.svg: Unsupported image format
file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Error decoding: file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/icons/file/folder_open.svg: Unsupported image format
file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/ToolButton.qml: QML IconImage: Error decoding: file:///tmp/.mount_Liri_CWGnMMi/usr/qml/Fluid/Controls/icons/action/info_outline.svg: Unsupported image format
qrc:/ui/Main.qml:191: SyntaxError: JSON.parse: Parse error
```

Icons are installed in `/usr/lib/x86_64-linux-gnu/qt5/qml/Fluid/Controls/icons` really.

Will debug this problem later.

**Comment by plfiorini** [comment] 2018-04-05 07:13
@probonopd Unfortunately finding an updated Qt for Ubuntu 14.04 which is a 4 years old system is nearly impossible or would require building large modules from sources making the CI provisioning slower than the actual build which doesn't make sense to me. We are using Ubuntu 16.04 with the KDE Neon repository.

**Comment by probonopd** [comment] 2018-04-06 09:03
> Unfortunately finding an updated Qt for Ubuntu 14.04 which is a 4 years old system is nearly impossible

err, no:
https://launchpad.net/~beineri

**Comment by plfiorini** [comment] 2018-04-06 10:00
I know it we used it before but qbs is still 1.7.2.
Building qbs from sources is out of the question.

**Comment by probonopd** [comment] 2018-04-06 10:05
Then your application is not targeting the oldest still-available Ubuntu LTS release. You still can make an AppImage but it cannot be included in AppImageHub, since those applications are targeting the oldest still-available Ubuntu LTS release, and newer.

**Comment by plfiorini** [comment] 2018-04-06 10:13
No problem users will just download it from our web site

**Comment by plfiorini** [comment] 2018-05-06 17:05
The svg problem is resolved with: https://github.com/probonopd/linuxdeployqt/issues/82#issuecomment-289317542 - infra-travis now copies the QtSvg plugins

**Closed** 2018-05-06 17:05 UTC
Labels: package
